# Generated by Django 6.1 on 2026-09-12 14:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('scale', models.CharField(choices=[('international', 'International'), ('national', 'National'), ('provincial', 'Provincial'), ('district', 'District')], default='national', max_length=20)),
                ('date_achieved', models.DateField()),
                ('issuer', models.CharField(max_length=255)),
            ],
        ),
    ]
